### PR TITLE
Using matrix to simplify yaml file

### PR DESCRIPTION
**Pull request by sophia-guo**
Signed-off-by: Sophia Guo <sophiag@ca.ibm.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
Ideally using exclude https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-excluding-configurations-from-a-matrix would be even simplier:

```
     strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, macos-10.15, windows-2016]
        javaToBuild: [jdk11u, jdk14u]
        impl: [hotspot, openj9]
        exclude:
            -os: windows-2016
              impl: openj9

```

However the exclude doesn't work as expected: exclude cross product of each configuration.

**Comment by sophia-guo** [comment]
some tests:
https://github.com/sophia-guo/runaqa/runs/866713888?check_suite_focus=true

**Comment by sophia-guo** [comment]
@smlambert could you please take a look at this? Thanks.

**Comment by smlambert** [comment]
@sophia-guo - https://github.com/AdoptOpenJDK/build-jdk/runs/972958891 - I guess I am missing seeing these before merging?

**Pull request merged**
